language: node_js
sudo: false
dist: trusty

node_js:
  - '8'

addons:
  chrome: stable

jobs:
  include:
    - env: "PHASE=lint"
    - env: "PHASE=aot"
    - env: "PHASE=unit"
    - env: "PHASE=lib_build"
#    - env: "PHASE=e2e"

install:
  - npm install

script:
  - ./scripts/travis-script.sh

cache:
  directories:
    - ./node_modules/